using GestionStock.Web.Models;

namespace GestionStock.Web.Services;

public interface IApiService
{
    Task<DashboardDto?> GetDashboardAsync();
    Task<PagedResult<ArticleDto>?> GetArticlesAsync(int page = 1, int pageSize = 20, string? search = null, string? categorie = null);
    Task<ArticleDto?> GetArticleAsync(Guid id);
    Task<IEnumerable<AlerteStockDto>?> GetArticlesEnAlerteAsync();
    Task<ResultDto?> CreerArticleAsync(CreerArticleDto dto);
    Task<ResultDto?> ModifierArticleAsync(Guid id, ModifierArticleDto dto);
    Task<ResultDto?> DesactiverArticleAsync(Guid id);
    Task<IEnumerable<StockResumeDto>?> GetStocksResumeAsync();
    Task<IEnumerable<MouvementStockDto>?> GetMouvementsAsync(Guid? articleId = null, DateTime? du = null, DateTime? au = null);
    Task<IEnumerable<DocumentStockDto>?> GetDocumentsStockAsync(DateTime? du = null, DateTime? au = null, int? type = null, string? q = null);
    Task<DocumentStockDto?> GetDocumentStockAsync(Guid id);
    Task<ResultDto?> ValiderDocumentStockAsync(Guid id);
    Task<ResultDto?> CreerDocumentEntreeStockAsync(DocumentEntreeStockRequest dto);
    Task<ResultDto?> EntreeStockAsync(EntreeStockDto dto);
    Task<ResultDto?> SortieStockAsync(SortieStockDto dto);
    Task<PagedResult<FournisseurDto>?> GetFournisseursAsync(int page = 1, int pageSize = 20, string? search = null);
    Task<ResultDto?> CreerFournisseurAsync(CreerFournisseurDto dto);
    Task<ResultDto?> ModifierFournisseurAsync(Guid id, CreerFournisseurDto dto);
    Task<PagedResult<CommandeAchatDto>?> GetCommandesAsync(int page = 1, int pageSize = 20);
    Task<IEnumerable<CommandeAchatDto>?> GetCommandesEnAttenteAsync();
    Task<CommandeAchatDto?> GetCommandeAsync(Guid id);
    Task<ResultDto?> CreerCommandeAsync(CreerCommandeDto dto);
    Task<ResultDto?> ModifierCommandeAsync(Guid id, CreerCommandeDto dto);
    Task<ResultDto?> ValiderCommandeAsync(Guid id);
    Task<ResultDto?> ComptabiliserCommandeAsync(Guid id);
    Task<ResultDto?> AnnulerCommandeAsync(Guid id, string motif);
    Task<ParametresDto?> GetParametresAsync();
    Task<ResultDto?> SauvegarderParametresAsync(ParametresDto dto);
    Task<InscriptionResultat?> InscrireAsync(InscriptionRequest dto);
    Task<bool> EmailDisponibleAsync(string email);
    Task<List<TenantDto>?> GetTenantsAsync();
    Task<TenantDetailDto?> GetTenantDetailAsync(string code);
    Task<ResultDto?> CreerTenantAsync(TenantCreateRequest dto);
    Task<ResultDto?> ActiverTenantAsync(string code);
    Task<ResultDto?> SusprendreTenantAsync(string code);
    Task<ResultDto?> SupprimerTenantAsync(string code);
    Task<ResultDto?> ResetPasswordTenantAsync(string code, string motDePasse);
    Task<List<UtilisateurDto>?> GetUtilisateursAsync();
    Task<List<RoleDto>?> GetRolesAsync();
    Task<ResultDto?> CreerUtilisateurAsync(UtilisateurRequest dto);
    Task<ResultDto?> ModifierUtilisateurAsync(string id, ModifierUtilisateurRequest dto);
    Task<ResultDto?> ResetMdpUtilisateurAsync(string id, string mdp);
    Task<ResultDto?> ActiverUtilisateurAsync(string id);
    Task<ResultDto?> DesactiverUtilisateurAsync(string id);
    Task<ResultDto?> DeverrouillerUtilisateurAsync(string id);
    Task<ResultDto?> ChangerMotDePasseAsync(string ancien, string nouveau);
    Task<string[]?> GetCataloguePermissionsAsync();
    Task<PermissionsDetailDto?> GetPermissionsRoleAsync(int roleId);
    Task<ResultDto?> SetPermissionsRoleAsync(int roleId, string[] permissions);
    Task<PermissionsDetailDto?> GetPermissionsUtilisateurAsync(string userId);
    Task<ResultDto?> SetPermissionsUtilisateurAsync(string userId, string[] permissions, bool reset = false);
    Task<List<ClientDto>?> GetClientsAsync(string? q = null);
    Task<ResultDto?> CreerClientAsync(ClientRequest dto);
    Task<ResultDto?> ModifierClientAsync(Guid id, ClientRequest dto);
    Task<List<DocumentVenteDto>?> GetVentesAsync(int? type = null, int? statut = null, Guid? clientId = null, string? q = null);
    Task<DocumentVenteDetailDto?> GetVenteAsync(Guid id);
    Task<ResultDto?> CreerVenteAsync(DocumentVenteRequest dto);
    Task<ResultDto?> ModifierVenteAsync(Guid id, DocumentVenteRequest dto);
    Task<ResultDto?> ValiderVenteAsync(Guid id);
    Task<ResultDto?> ComptabiliserVenteAsync(Guid id);
    Task<ResultDto?> AnnulerVenteAsync(Guid id);
    Task<ResultDto?> TransformerVenteAsync(Guid id, int typeDoc);
    Task<ResultDto?> AjouterReglementVenteAsync(Guid id, ReglementRequest dto);
    Task<List<DocumentAchatDto>?> GetAchatsCommAsync(int? type = null);
    Task<DocumentAchatDetailDto?> GetAchatCommAsync(Guid id);
    Task<ResultDto?> CreerAchatCommAsync(DocumentAchatRequest dto);
    Task<ResultDto?> ModifierAchatCommAsync(Guid id, DocumentAchatRequest dto);
    Task<ResultDto?> TransformerAchatCommAsync(Guid id, int typeDoc);
    Task<CommercialDashboardDto?> GetCommercialDashboardAsync();
    Task<List<ReglementDto>?> GetReglementsAsync(Guid? documentId = null, int? typeDocument = null);
    Task<ResultDto?> SupprimerReglementAsync(Guid id);
    Task<List<AcompteDto>?> GetAcomptesAsync(Guid? clientId = null, Guid? fournisseurId = null, bool nonUtilisesSeulement = false);
    Task<ResultDto?> CreerAcompteAsync(AcompteRequest dto);
    Task<ResultDto?> ImputerAcompteAsync(Guid acompteId, Guid documentId, decimal montant);
    Task<ComptabiliteDto?> GetComptabiliteAsync();
    Task<ResultDto?> SauvegarderComptabiliteAsync(ComptabiliteDto dto);
    Task<List<RoleCompletDto>?> GetRolesCompletAsync();
    Task<ResultDto?> CreerRoleAsync(RoleRequest dto);
    Task<ResultDto?> ModifierRoleAsync(int id, RoleRequest dto);
    Task<ResultDto?> ActiverRoleAsync(int id);
    Task<ResultDto?> DesactiverRoleAsync(int id);
    Task<ResultDto?> SupprimerRoleAsync(int id);
    Task<List<LotTracabiliteDto>?> GetLotsAsync(Guid? articleId = null, bool alertePeremption = false);
    Task<List<AlertePeremptionDto>?> GetAlertesPeremptionAsync(int joursAvance = 30);
    Task<ResultDto?> CreerLotAsync(LotRequest dto);
    Task<ResultDto?> ModifierStatutLotAsync(Guid lotId, int statut);
    Task<List<MouvementTracabiliteDto>?> GetMouvementsLotAsync(Guid lotId);
    Task<object?> GetFicheTracabiliteAsync(Guid articleId, DateTime? du, DateTime? au);
    Task<List<CategorieDto>?> GetCategoriesAsync(bool actifSeulement = true);
    Task<ResultDto?> CreerCategorieAsync(CategorieRequest dto);
    Task<ResultDto?> ModifierCategorieAsync(Guid id, CategorieRequest dto);
    Task<ResultDto?> DesactiverCategorieAsync(Guid id);
    Task<List<EmplacementDto>?> GetEmplacementsAsync();
    Task<ResultDto?> TransfertStockAsync(TransfertRequest dto);
    Task<ResultDto?> AjustementStockAsync(AjustementRequest dto);
    Task<List<DepotDto>?> GetDepotsAsync(bool actifSeulement = true);
    Task<ResultDto?> CreerDepotAsync(DepotRequest dto);
    Task<ResultDto?> ModifierDepotAsync(Guid id, DepotRequest dto);
    Task<ResultDto?> DefinirDepotPrincipalAsync(Guid id);
    Task<ResultDto?> DesactiverDepotAsync(Guid id);
    Task<List<FamilleArticleDto>?> GetFamillesAsync(bool actifSeulement = true);
    Task<ResultDto?> CreerFamilleAsync(FamilleRequest dto);
    Task<ResultDto?> ModifierFamilleAsync(Guid id, FamilleRequest dto);
    Task<ResultDto?> DesactiverFamilleAsync(Guid id);
}

